#!/usr/bin/env python3
"""Create an organ-wise jitter plot from cycle error CSV output."""

import argparse
import csv
import os
from collections import defaultdict
from statistics import median

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def strip_nii_suffix(filename):
    if filename.endswith(".nii.gz"):
        return filename[:-7]
    if filename.endswith(".nii"):
        return filename[:-4]
    return filename


def extract_organ_name(mask_name):
    base = os.path.basename(mask_name)
    return strip_nii_suffix(base)


def load_organ_errors(csv_path, error_column):
    organ_to_errors = defaultdict(list)

    with open(csv_path, "r", newline="") as f:
        reader = csv.DictReader(f)
        if error_column not in (reader.fieldnames or []):
            raise ValueError(
                f"Column '{error_column}' not found in CSV. "
                f"Available columns: {reader.fieldnames}"
            )
        if "mask_name" not in (reader.fieldnames or []):
            raise ValueError(
                f"Column 'mask_name' not found in CSV. Available columns: {reader.fieldnames}"
            )

        for row in reader:
            mask_name = row.get("mask_name", "")
            err_str = row.get(error_column, "")
            if not mask_name or not err_str:
                continue
            try:
                err_val = float(err_str)
            except ValueError:
                continue
            organ = extract_organ_name(mask_name)
            organ_to_errors[organ].append(err_val)

    if not organ_to_errors:
        raise RuntimeError(f"No valid rows found in CSV: {csv_path}")
    return organ_to_errors


def order_organs(organ_to_errors, mode):
    organs = list(organ_to_errors.keys())
    if mode == "name":
        return sorted(organs)
    if mode == "median":
        return sorted(organs, key=lambda k: median(organ_to_errors[k]))
    raise ValueError(f"Unsupported order mode: {mode}")


def make_jitter_plot(
    organ_to_errors,
    output_path,
    ylabel,
    title,
    jitter=0.18,
    alpha=0.65,
    point_size=8,
    seed=0,
    order_mode="name",
    show=False,
):
    organs = order_organs(organ_to_errors, order_mode)
    n_organs = len(organs)

    fig_w = max(8.0, min(0.85 * n_organs + 3.0, 20.0))
    fig, ax = plt.subplots(figsize=(fig_w, 6))

    rng = np.random.default_rng(seed)
    cmap = plt.get_cmap("tab10")

    for idx, organ in enumerate(organs):
        y = np.asarray(organ_to_errors[organ], dtype=float)
        x = idx + rng.uniform(-jitter, jitter, size=len(y))
        ax.scatter(
            x,
            y,
            s=point_size,
            alpha=alpha,
            color=cmap(idx % 10),
            edgecolors="none",
        )

    ax.set_xlim(-0.5, n_organs - 0.5)
    ax.set_xticks(np.arange(n_organs))
    ax.set_xticklabels(organs, rotation=35, ha="right")
    ax.set_xlabel("Organ (mask)")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(axis="y", linestyle="--", alpha=0.35)

    fig.tight_layout()
    fig.savefig(output_path, dpi=200, bbox_inches="tight")

    if show:
        plt.show()
    plt.close(fig)


def build_parser():
    parser = argparse.ArgumentParser(
        description="Plot organ-wise jitter distribution from cycle error CSV."
    )
    parser.add_argument(
        "--csv",
        type=str,
        required=True,
        help="Path to cycle_points_*.csv generated by inc_cycle_error.py",
    )
    parser.add_argument(
        "--ycol",
        type=str,
        default="mm_error",
        choices=["mm_error", "voxel_error"],
        help="CSV column to plot on y-axis",
    )
    parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output figure path (.png). Defaults to <csv_stem>_jitter_<ycol>.png",
    )
    parser.add_argument(
        "--order",
        type=str,
        default="name",
        choices=["name", "median"],
        help="Order organs by name or by median error",
    )
    parser.add_argument("--title", type=str, default=None, help="Custom plot title")
    parser.add_argument(
        "--jitter",
        type=float,
        default=0.18,
        help="Horizontal jitter half-width in x-axis units",
    )
    parser.add_argument("--alpha", type=float, default=0.65, help="Point alpha")
    parser.add_argument("--size", type=float, default=8.0, help="Point size")
    parser.add_argument("--seed", type=int, default=0, help="Random seed for jitter")
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the figure in an interactive window",
    )
    return parser


def main():
    args = build_parser().parse_args()
    csv_path = args.csv
    if not os.path.isfile(csv_path):
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    default_out = (
        f"{os.path.splitext(csv_path)[0]}_jitter_{args.ycol}.png"
        if args.out is None
        else args.out
    )
    title = (
        args.title
        if args.title
        else f"Cycle Error Jitter by Organ ({args.ycol})"
    )
    ylabel = "Cycle Error (mm)" if args.ycol == "mm_error" else "Cycle Error (voxel)"

    organ_to_errors = load_organ_errors(csv_path, args.ycol)
    make_jitter_plot(
        organ_to_errors=organ_to_errors,
        output_path=default_out,
        ylabel=ylabel,
        title=title,
        jitter=args.jitter,
        alpha=args.alpha,
        point_size=args.size,
        seed=args.seed,
        order_mode=args.order,
        show=args.show,
    )
    print(f"Saved jitter plot to: {default_out}")
    print(f"Organs plotted: {len(organ_to_errors)}")


if __name__ == "__main__":
    main()
